package main

import (
	"bufio"
	"encoding/binary"
	"fmt"
	"io"
	"math/bits"
	"net/netip"
	"os"
	"path/filepath"
	"strconv"
	"time"
)

const (
	mmdbRecordSize        = 28
	mmdbDataSeparatorSize = 16
	mmdbDescription       = "IPinfo Lite country, continent, and ASN database. Data source: https://ipinfo.io/lite; generated by: https://github.com/Alice39s/ipinfo-csv-lite; data license: https://creativecommons.org/licenses/by-sa/4.0/"
	mmdbNodeRef           = uint32(1 << 30)
	mmdbDataRef           = uint32(2 << 30)
	mmdbRefMask           = uint32(3 << 30)
	mmdbValueMask         = ^mmdbRefMask
)

var mmdbMetadataMarker = []byte("\xAB\xCD\xEFMaxMind.com")

// runMmdb converts data/ipinfo-lite.csv into a MaxMind DB file. This writer is
// specialized for the pipeline's fixed flat record shape and IPv6 search tree;
// avoiding a generic per-prefix object tree keeps multi-million-row builds fast.
func runMmdb() error {
	input := filepath.Join(dataDir, "ipinfo-lite.csv")
	output := filepath.Join(dataDir, "ipinfo-lite.mmdb")

	inserted, skipped, err := writeMmdb(input, output, time.Now().Unix())
	if err != nil {
		return err
	}
	fmt.Printf("Wrote %s (%d networks, %d skipped)\n", output, inserted, skipped)
	return nil
}

type mmdbRecord struct {
	countryCode   string
	continentCode string
	asNumber      uint32
	asName        string
}

type mmdbNode struct {
	child [2]uint32
}

type mmdbBuilder struct {
	nodes   []mmdbNode
	data    []byte
	records map[mmdbRecord]uint32
	strings map[string]uint32
}

func newMmdbBuilder() *mmdbBuilder {
	b := &mmdbBuilder{
		nodes:   make([]mmdbNode, 1, 1<<21),
		data:    make([]byte, 0, 1<<24),
		records: make(map[mmdbRecord]uint32, 1<<17),
		strings: make(map[string]uint32, 1<<17),
	}
	// Store the fixed field names once. Every record points back to these four
	// scalars, avoiding several megabytes of repeated map-key bytes.
	for _, field := range []string{"as_name", "as_number", "continent_code", "country_code"} {
		b.strings[field] = uint32(len(b.data))
		b.data = appendMmdbString(b.data, field)
	}
	return b
}

func writeMmdb(input, output string, buildEpoch int64) (inserted, skipped int, err error) {
	fIn, reader, err := openLiteCSV(input, true)
	if err != nil {
		return 0, 0, err
	}
	defer fIn.Close()

	generator := newMmdbGenerator()
	for {
		row, readErr := reader.Read()
		if readErr == io.EOF {
			break
		}
		if readErr != nil {
			return inserted, skipped, readErr
		}
		if err := generator.addRow(row); err != nil {
			return generator.inserted, generator.skipped, err
		}
	}
	err = generator.writeTo(output, buildEpoch)
	return generator.inserted, generator.skipped, err
}

type mmdbGenerator struct {
	builder           *mmdbBuilder
	inserted, skipped int
	lastAddress       [16]byte
	lastBits          int
	path              [129]uint32
	hasLast           bool
}

func newMmdbGenerator() *mmdbGenerator {
	return &mmdbGenerator{builder: newMmdbBuilder()}
}

func (g *mmdbGenerator) addRow(row []string) error {
	if len(row) < 5 || row[0] == "" {
		g.skipped++
		return nil
	}
	prefix, err := parseLitePrefix(row[0])
	if err != nil {
		g.skipped++
		return nil
	}
	record := mmdbRecordFromRow(row)
	if err := g.insertSorted(prefix, g.builder.recordRef(record)); err != nil {
		return fmt.Errorf("insert %s: %w", row[0], err)
	}
	g.inserted++
	return nil
}

// insertSorted caches the node path shared with the previous prefix. IPinfo's
// rows are address-sorted, so adjacent networks commonly share most leading
// bits; avoiding a fresh root traversal for every row saves millions of node
// lookups. Overlapping prefixes conservatively restart at the root.
func (g *mmdbGenerator) insertSorted(prefix netip.Prefix, value uint32) error {
	addr, prefixBits := mmdbAddress(prefix)
	if prefixBits == 0 {
		g.builder.nodes[0].child = [2]uint32{value, value}
		g.hasLast = false
		return nil
	}

	startDepth := 0
	if g.hasLast {
		common := commonPrefixBits(g.lastAddress, addr)
		if common < min(g.lastBits, prefixBits) {
			startDepth = min(common, g.lastBits-1, prefixBits-1)
		}
	}
	nodeIndex := g.path[startDepth]
	for depth := startDepth; depth < prefixBits; depth++ {
		bit := (addr[depth/8] >> (7 - uint(depth%8))) & 1
		if depth == prefixBits-1 {
			g.builder.nodes[nodeIndex].child[bit] = value
			break
		}

		child := g.builder.nodes[nodeIndex].child[bit]
		parent := nodeIndex
		switch child & mmdbRefMask {
		case mmdbNodeRef:
			nodeIndex = child & mmdbValueMask
		case mmdbDataRef:
			nodeIndex = g.builder.appendNode(mmdbNode{child: [2]uint32{child, child}})
			g.builder.nodes[parent].child[bit] = mmdbNodeRef | nodeIndex
		default:
			nodeIndex = g.builder.appendNode(mmdbNode{})
			g.builder.nodes[parent].child[bit] = mmdbNodeRef | nodeIndex
		}
		g.path[depth+1] = nodeIndex
	}
	g.lastAddress = addr
	g.lastBits = prefixBits
	g.hasLast = true
	return nil
}

func commonPrefixBits(a, b [16]byte) int {
	for i := range a {
		if a[i] != b[i] {
			return i*8 + bits.LeadingZeros8(a[i]^b[i])
		}
	}
	return 128
}

func (g *mmdbGenerator) writeTo(output string, buildEpoch int64) error {
	if err := g.builder.addIPv4Aliases(); err != nil {
		return err
	}
	return g.builder.writeTo(output, buildEpoch)
}

func writeMmdbBatches(rows <-chan [][]string, output string, buildEpoch int64) (inserted, skipped int, err error) {
	generator := newMmdbGenerator()
	for batch := range rows {
		for _, row := range batch {
			if err := generator.addRow(row); err != nil {
				return generator.inserted, generator.skipped, err
			}
		}
	}
	err = generator.writeTo(output, buildEpoch)
	return generator.inserted, generator.skipped, err
}

func mmdbRecordFromRow(row []string) mmdbRecord {
	asNumber, err := strconv.ParseUint(row[3], 10, 32)
	if err != nil {
		asNumber = 0
	}
	return mmdbRecord{
		countryCode:   row[1],
		continentCode: row[2],
		asNumber:      uint32(asNumber),
		asName:        row[4],
	}
}

func (b *mmdbBuilder) recordRef(record mmdbRecord) uint32 {
	if offset, ok := b.records[record]; ok {
		return mmdbDataRef | offset
	}
	offset := uint32(len(b.data))
	b.appendRecord(record)
	b.records[record] = offset
	return mmdbDataRef | offset
}

func (b *mmdbBuilder) insert(prefix netip.Prefix, value uint32) error {
	addr, bits := mmdbAddress(prefix)
	if bits == 0 {
		b.nodes[0].child = [2]uint32{value, value}
		return nil
	}

	nodeIndex := uint32(0)
	for depth := range bits {
		bit := (addr[depth/8] >> (7 - uint(depth%8))) & 1
		if depth == bits-1 {
			b.nodes[nodeIndex].child[bit] = value
			return nil
		}

		child := b.nodes[nodeIndex].child[bit]
		switch child & mmdbRefMask {
		case mmdbNodeRef:
			nodeIndex = child & mmdbValueMask
		case mmdbDataRef:
			parent := nodeIndex
			nodeIndex = b.appendNode(mmdbNode{child: [2]uint32{child, child}})
			b.nodes[parent].child[bit] = mmdbNodeRef | nodeIndex
		default:
			parent := nodeIndex
			nodeIndex = b.appendNode(mmdbNode{})
			b.nodes[parent].child[bit] = mmdbNodeRef | nodeIndex
		}
	}
	return nil
}

func (b *mmdbBuilder) appendNode(node mmdbNode) uint32 {
	index := uint32(len(b.nodes))
	b.nodes = append(b.nodes, node)
	return index
}

func mmdbAddress(prefix netip.Prefix) (addr [16]byte, bits int) {
	if prefix.Addr().Is4() {
		v4 := prefix.Addr().As4()
		copy(addr[12:], v4[:])
		return addr, prefix.Bits() + 96
	}
	return prefix.Addr().As16(), prefix.Bits()
}

func (b *mmdbBuilder) addIPv4Aliases() error {
	v4Root, err := b.refAtPrefix(netip.MustParsePrefix("::/96"))
	if err != nil || v4Root == 0 {
		return err
	}
	for _, alias := range []string{"::ffff:0:0/96", "2001::/32", "2002::/16"} {
		if err := b.insert(netip.MustParsePrefix(alias), v4Root); err != nil {
			return fmt.Errorf("insert IPv4 alias %s: %w", alias, err)
		}
	}
	return nil
}

func (b *mmdbBuilder) refAtPrefix(prefix netip.Prefix) (uint32, error) {
	addr, bits := mmdbAddress(prefix)
	if bits == 0 {
		return mmdbNodeRef, nil
	}
	nodeIndex := uint32(0)
	for depth := range bits {
		bit := (addr[depth/8] >> (7 - uint(depth%8))) & 1
		ref := b.nodes[nodeIndex].child[bit]
		if depth == bits-1 || ref&mmdbRefMask != mmdbNodeRef {
			return ref, nil
		}
		nodeIndex = ref & mmdbValueMask
	}
	return 0, nil
}

func (b *mmdbBuilder) writeTo(path string, buildEpoch int64) error {
	nodeCount := uint32(len(b.nodes))
	maxPointer := uint64(nodeCount) + mmdbDataSeparatorSize + uint64(len(b.data))
	if maxPointer >= 1<<mmdbRecordSize {
		return fmt.Errorf("MMDB exceeds %d-bit record capacity", mmdbRecordSize)
	}

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	w := bufio.NewWriterSize(f, 1<<20)
	fail := func(err error) error {
		_ = f.Close()
		return err
	}

	var encoded [7]byte
	for _, node := range b.nodes {
		left := b.resolveRef(node.child[0], nodeCount)
		right := b.resolveRef(node.child[1], nodeCount)
		encodeMmdbNode(encoded[:], left, right)
		if _, err := w.Write(encoded[:]); err != nil {
			return fail(err)
		}
	}
	if _, err := w.Write(make([]byte, mmdbDataSeparatorSize)); err != nil {
		return fail(err)
	}
	if _, err := w.Write(b.data); err != nil {
		return fail(err)
	}
	if _, err := w.Write(mmdbMetadataMarker); err != nil {
		return fail(err)
	}
	if _, err := w.Write(appendMmdbMetadata(nil, nodeCount, buildEpoch)); err != nil {
		return fail(err)
	}
	if err := w.Flush(); err != nil {
		return fail(err)
	}
	if err := f.Close(); err != nil {
		return err
	}
	return nil
}

func (b *mmdbBuilder) resolveRef(ref, nodeCount uint32) uint32 {
	switch ref & mmdbRefMask {
	case mmdbNodeRef:
		return ref & mmdbValueMask
	case mmdbDataRef:
		return nodeCount + mmdbDataSeparatorSize + ref&mmdbValueMask
	default:
		return nodeCount
	}
}

func encodeMmdbNode(dst []byte, left, right uint32) {
	dst[0] = byte(left >> 16)
	dst[1] = byte(left >> 8)
	dst[2] = byte(left)
	dst[3] = byte((left>>24)<<4 | right>>24)
	dst[4] = byte(right >> 16)
	dst[5] = byte(right >> 8)
	dst[6] = byte(right)
}

func (b *mmdbBuilder) appendRecord(record mmdbRecord) {
	fields := 1
	if record.asName != "" {
		fields++
	}
	if record.continentCode != "" {
		fields++
	}
	if record.countryCode != "" {
		fields++
	}
	b.data = appendMmdbControl(b.data, 7, fields)
	if record.asName != "" {
		b.data = appendMmdbPointer(b.data, b.strings["as_name"])
		b.appendString(record.asName)
	}
	b.data = appendMmdbPointer(b.data, b.strings["as_number"])
	b.data = appendMmdbUint(b.data, 6, uint64(record.asNumber))
	if record.continentCode != "" {
		b.data = appendMmdbPointer(b.data, b.strings["continent_code"])
		b.appendString(record.continentCode)
	}
	if record.countryCode != "" {
		b.data = appendMmdbPointer(b.data, b.strings["country_code"])
		b.appendString(record.countryCode)
	}
}

func (b *mmdbBuilder) appendString(value string) {
	if offset, ok := b.strings[value]; ok && mmdbPointerSize(offset) < len(value)+1 {
		b.data = appendMmdbPointer(b.data, offset)
		return
	}
	if _, ok := b.strings[value]; !ok {
		b.strings[value] = uint32(len(b.data))
	}
	b.data = appendMmdbString(b.data, value)
}

func mmdbPointerSize(offset uint32) int {
	switch {
	case offset < 1<<11:
		return 2
	case offset < (1<<11)+(1<<19):
		return 3
	case offset < (1<<11)+(1<<19)+(1<<27):
		return 4
	default:
		return 5
	}
}

func appendMmdbPointer(dst []byte, offset uint32) []byte {
	switch {
	case offset < 1<<11:
		return append(dst, 0x20|byte(offset>>8), byte(offset))
	case offset < (1<<11)+(1<<19):
		value := offset - (1 << 11)
		return append(dst, 0x28|byte(value>>16), byte(value>>8), byte(value))
	case offset < (1<<11)+(1<<19)+(1<<27):
		value := offset - (1 << 11) - (1 << 19)
		return append(dst, 0x30|byte(value>>24), byte(value>>16), byte(value>>8), byte(value))
	default:
		return append(dst, 0x38, byte(offset>>24), byte(offset>>16), byte(offset>>8), byte(offset))
	}
}

func appendMmdbMetadata(dst []byte, nodeCount uint32, buildEpoch int64) []byte {
	dst = appendMmdbControl(dst, 7, 9)
	dst = appendMmdbString(dst, "binary_format_major_version")
	dst = appendMmdbUint(dst, 5, 2)
	dst = appendMmdbString(dst, "binary_format_minor_version")
	dst = appendMmdbUint(dst, 5, 0)
	dst = appendMmdbString(dst, "build_epoch")
	dst = appendMmdbUint(dst, 9, uint64(buildEpoch))
	dst = appendMmdbString(dst, "database_type")
	dst = appendMmdbString(dst, "ipinfo-lite")
	dst = appendMmdbString(dst, "description")
	dst = appendMmdbControl(dst, 7, 1)
	dst = appendMmdbString(dst, "en")
	dst = appendMmdbString(dst, mmdbDescription)
	dst = appendMmdbString(dst, "ip_version")
	dst = appendMmdbUint(dst, 5, 6)
	dst = appendMmdbString(dst, "languages")
	dst = appendMmdbControl(dst, 11, 1)
	dst = appendMmdbString(dst, "en")
	dst = appendMmdbString(dst, "node_count")
	dst = appendMmdbUint(dst, 6, uint64(nodeCount))
	dst = appendMmdbString(dst, "record_size")
	return appendMmdbUint(dst, 5, mmdbRecordSize)
}

func appendMmdbString(dst []byte, value string) []byte {
	dst = appendMmdbControl(dst, 2, len(value))
	return append(dst, value...)
}

func appendMmdbUint(dst []byte, typeNumber byte, value uint64) []byte {
	size := 0
	for remaining := value; remaining != 0; remaining >>= 8 {
		size++
	}
	dst = appendMmdbControl(dst, typeNumber, size)
	var encoded [8]byte
	binary.BigEndian.PutUint64(encoded[:], value)
	return append(dst, encoded[len(encoded)-size:]...)
}

func appendMmdbControl(dst []byte, typeNumber byte, size int) []byte {
	first := byte(0)
	if typeNumber < 8 {
		first = typeNumber << 5
	}
	remaining, remainingSize := 0, 0
	switch {
	case size < 29:
		first |= byte(size)
	case size < 285:
		first |= 29
		remaining, remainingSize = size-29, 1
	case size < 65821:
		first |= 30
		remaining, remainingSize = size-285, 2
	default:
		first |= 31
		remaining, remainingSize = size-65821, 3
	}
	dst = append(dst, first)
	if typeNumber >= 8 {
		dst = append(dst, typeNumber-7)
	}
	for i := remainingSize - 1; i >= 0; i-- {
		dst = append(dst, byte(remaining>>(8*i)))
	}
	return dst
}
